name: arb_editor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # routing
  go_router: ^12.1.1

  yaml: ^3.1.2
  date_format: ^2.0.7
  collection: ^1.18.0
  supercharged: ^2.1.1
  json_annotation: ^4.8.1
  path: ^1.8.2
  uuid: ^4.2.1
  equatable: ^2.0.5

  file_picker: ^6.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  riverpod: ^2.4.6
  flutter_riverpod: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
