name: arb_editor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: '>=2.18.0 <3.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # routing
  go_router: ^9.0.3

  yaml: ^3.1.2
  date_format: ^2.0.7
  collection: ^1.16.0
  supercharged: ^2.1.1
  json_annotation: ^4.8.1
  path: ^1.8.2
  uuid: ^3.0.7
  equatable: ^2.0.5

  file_picker: ^5.3.2
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0

  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  go_router_builder: ^2.2.2

flutter:
  uses-material-design: true
