name: arb_editor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: '>=2.18.0 <3.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # routing
  go_router: ^6.5.9

  yaml: ^3.1.1
  date_format: ^2.0.7
  collection: ^1.16.0
  supercharged: ^2.1.1
  json_annotation: ^4.8.0
  path: ^1.8.2
  uuid: ^3.0.7
  equatable: ^2.0.5

  file_picker: ^5.2.11
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0

  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  go_router_builder: ^1.2.2

flutter:
  uses-material-design: true
